Extract OpenRouter model names, to obtain a human-readable name for each model
symflower/eval-dev-quality pull request #217
Opened 2024-06-25 17:03 UTC by ruiAzevedo19

Part of #206

2024-06-25 17:11 UTC, ruiAzevedo19 commented
Based on https://github.com/symflower/eval-dev-quality/pull/216

2024-06-26 07:00 UTC, bauersimon requested changes

2024-06-26 07:00 UTC, bauersimon commented on model/llm/llm.go
> +}
I think you will essentially have two constructors. One bare-minimum for the ID (that also the openai API provider can use). And then another one with all the additional information.

2024-06-26 07:01 UTC, bauersimon commented on model/llm/llm.go
> +}
TODO this also needs to go into the CSV

2024-06-26 07:02 UTC, bauersimon commented
Please try this out with the cheapest model from openrouter and post the CSV here to see how it looks like.

2024-06-26 10:43 UTC, ruiAzevedo19 commented
@bauersimon Results

### OpenRouter

**Command**
```
eval-dev-quality evaluate --runs 1 --repository golang/plain --model openrouter/meta-llama/llama-3-8b-instruct
```

<details><summary>evaluation.csv</summary>

```
model-name,model-id,cost,language,repository,task,score,coverage,files-executed,generate-tests-for-file-character-count,processing-time,response-character-count,response-no-error,response-no-excess,response-with-code
Meta: Llama 3 8B Instruct,openrouter/meta-llama/llama-3-8b-instruct,0.00000014,golang,golang/plain,write-tests,3,0,0,171,2114,181,1,1,1
```

</details>

<details><summary>golang-summed.csv</summary>

```
model-name,model-id,cost,score,coverage,files-executed,generate-tests-for-file-character-count,processing-time,response-character-count,response-no-error,response-no-excess,response-with-code
Meta: Llama 3 8B Instruct,openrouter/meta-llama/llama-3-8b-instruct,0.00000014,3,0,0,171,2114,181,1,1,1
```

</details>

<details><summary>models-summed.csv</summary>

```
model-name,model-id,cost,score,coverage,files-executed,generate-tests-for-file-character-count,processing-time,response-character-count,response-no-error,response-no-excess,response-with-code
Meta: Llama 3 8B Instruct,openrouter/meta-llama/llama-3-8b-instruct,0.00000014,3,0,0,171,2114,181,1,1,1
```

</details>

### Ollama

**Command**
```
eval-dev-quality evaluate --runs 1 --repository golang/plain --model ollama/qwen:0.5b
```

<details><summary>evaluation.csv</summary>

```
model-name,model-id,cost,language,repository,task,score,coverage,files-executed,generate-tests-for-file-character-count,processing-time,response-character-count,response-no-error,response-no-excess,response-with-code
qwen:0.5b,ollama/qwen:0.5b,0,golang,golang/plain,write-tests,2,0,0,155,8592,1041,1,0,1

```

</details>

<details><summary>golang-summed.csv</summary>

```
model-name,model-id,cost,score,coverage,files-executed,generate-tests-for-file-character-count,processing-time,response-character-count,response-no-error,response-no-excess,response-with-code
qwen:0.5b,ollama/qwen:0.5b,0,2,0,0,155,8592,1041,1,0,1
```

</details>

<details><summary>models-summed.csv</summary>

```
model-name,model-id,cost,score,coverage,files-executed,generate-tests-for-file-character-count,processing-time,response-character-count,response-no-error,response-no-excess,response-with-code
qwen:0.5b,ollama/qwen:0.5b,0,2,0,0,155,8592,1041,1,0,1
```

</details>

### OpenAi

**Command**
```
eval-dev-quality evaluate --runs 1 --repository golang/plain --urls custom-ollama:http://127.0.0.1:11434/v1 --model custom-ollama/qwen:0.5b

```

<details><summary>evaluation.csv</summary>

```
model-name,model-id,cost,language,repository,task,score,coverage,files-executed,generate-tests-for-file-character-count,processing-time,response-character-count,response-no-error,response-no-excess,response-with-code
qwen:0.5b,custom-ollama/qwen:0.5b,0,golang,golang/plain,write-tests,2,0,0,159,4697,600,1,0,1
```

</details>

<details><summary>golang-summed.csv</summary>

```
model-name,model-id,cost,score,coverage,files-executed,generate-tests-for-file-character-count,processing-time,response-character-count,response-no-error,response-no-excess,response-with-code
qwen:0.5b,custom-ollama/qwen:0.5b,0,2,0,0,159,4697,600,1,0,1
```

</details>

<details><summary>models-summed.csv</summary>

```
model-name,model-id,cost,score,coverage,files-executed,generate-tests-for-file-character-count,processing-time,response-character-count,response-no-error,response-no-excess,response-with-code
qwen:0.5b,custom-ollama/qwen:0.5b,0,2,0,0,159,4697,600,1,0,1
```

</details>

2024-06-26 10:49 UTC, bauersimon commented
Please still always put the model id first.

2024-06-26 10:50 UTC, bauersimon commented
Just asking myself if we should put the model names in quotes in the csv... As long as no name **contains** a `,` it should be good.

2024-06-26 10:52 UTC, bauersimon commented
> Just asking myself if we should put the model names in quotes in the csv... As long as no name **contains** a `,` it should be good.

Not necessary: https://pkg.go.dev/encoding/csv#Writer.Write.
Will quote as required.

2024-06-26 10:57 UTC, bauersimon requested changes

2024-06-26 10:57 UTC, bauersimon commented on cmd/eval-dev-quality/cmd/evaluate.go
> +			modelProvider.AddModel(llm.NewNamedModelWithCost(modelProvider, model, modelName[len(modelName)-1], 0))
Can use https://pkg.go.dev/strings#SplitN to get just the model name.

`strings.Split(model, provider.ProviderModelSeparator, 1)[1]`

2024-06-26 11:06 UTC, bauersimon approved these changes

2024-06-26 11:56 UTC, merged

2024-06-27 13:26 UTC, bauersimon commented on cmd/eval-dev-quality/cmd/evaluate.go
> +			modelProvider.AddModel(llm.NewNamedModelWithCost(modelProvider, model, modelName[len(modelName)-1], 0))
Wait why was this not resolved... I guess it should've been `strings.SplitN(model, provider.ProviderModelSeparator, 2)[1]`.