Do not run "symflower fix" if the original response failed with a timeout, so the model and the fix assessments are consistent
symflower/eval-dev-quality pull request #236
Opened 2024-07-02 14:45 UTC by ruiAzevedo19

Part of #232

2024-07-02 14:56 UTC, ruiAzevedo19 commented
@bauersimon I wanted to add a unit test for this case but I think it's not that easy:
- the execution timeout value is hard-coded, so in order to test the changes I would need to change `language.DefaultExecutionTimeout = <timeout-for-tests>` and then reset it to the original value. This approach sounds wrong
- I would need a scenario where the 1st call to the execution function (for the model)  times out, but the 2nd call (for `symflower fix`) does not. Not possible with the current implementation
- Also thought of a system test where we can set the execution time via CLI, but the value is in minutes.

2024-07-03 07:36 UTC, bauersimon commented on evaluate/task/task-write-test.go
> +			// If there is an execution timeout do not run "symflower fix".
`cause the code itself is correct`.

2024-07-03 07:49 UTC, bauersimon commented
I think one clean possibility would be to have the execution timeout as a method of the language interface and then use a mock of a language that can return a lower value. Can you try that out and if it takes longer then 10 minutes we just go with what we have? It's just an optimization for like a 1% chance. So not super duper important to test if it's such a hassle.

2024-07-03 08:42 UTC, ruiAzevedo19 commented
> I think one clean possibility would be to have the execution timeout as a method of the language interface and then use a mock of a language that can return a lower value. Can you try that out and if it takes longer then 10 minutes we just go with what we have? It's just an optimization for like a 1% chance. So not super duper important to test if it's such a hassle.

Did it a bit differently: I mocked the `Execute` function to return the timeout error and did the assertions accordingly. Reason being the timeout method would be called inside the `Execute` method, which needs also to be mocked.

2024-07-03 10:53 UTC, bauersimon requested changes

2024-07-03 10:53 UTC, bauersimon commented on evaluate/task/task-write-test_test.go
> +				validateGo(t, "Model generated test with unused import", languageMock, bytesutil.StringTrimIndentations(`
update test name to reflect timeout

2024-07-03 10:53 UTC, bauersimon commented on evaluate/task/task-write-test_test.go
> +					}
Please make this an empty string so it's clear that it is not used.

2024-07-03 11:18 UTC, bauersimon approved these changes

2024-07-04 06:02 UTC, merged