Add documentation for the code repair and transpile task
symflower/eval-dev-quality pull request #248
Opened 2024-07-08 16:23 UTC by ruiAzevedo19

2024-07-11 07:27 UTC, bauersimon requested changes

2024-07-11 07:27 UTC, bauersimon commented on README.md
>  Currently, the following points are awarded for this task:
`Currently, the following points are awarded for any task:`

also could you please change the coverage scoring below... it is not based on 100% anymore but what portions of the code is covered

2024-07-11 07:27 UTC, bauersimon commented on README.md
> +For this task, we introduced the `mistakes` repository, which includes five examples of source code with compilation errors for both Java and Go.
Would remove this sentence cause the number of examples and languages could change.

2024-07-11 07:27 UTC, bauersimon commented on README.md
>    - `plain/plain.go`: An empty function that does nothing.
We have more than the plain examples by now. Please add a commit where they are added `with pretty links`.

2024-07-11 07:27 UTC, bauersimon commented on README.md
> +  - [`golang/mistakes`](https://github.com/symflower/eval-dev-quality/tree/main/testdata/golang/mistakes)
Can you try to change the link to be relative? I.e. `[java/mistakes](testdata/java/mistakes)` cause I think GitHub will automatically make it a link to the folder. That way it stays correct on different branches.

2024-07-12 06:23 UTC, bauersimon commented
awesome! will merge after https://github.com/symflower/eval-dev-quality/pull/226 is in

2024-07-12 10:05 UTC, ruiAzevedo19 commented
Closing in favor of #264 and #226

2024-07-12 10:05 UTC, closed without merging