Remove the logic to write the markdown report, since it will be handled afterwards with tooling
symflower/eval-dev-quality pull request #258
Opened 2024-07-11 08:51 UTC by ruiAzevedo19

Part of #205

2024-07-11 08:52 UTC, ruiAzevedo19 commented
Based on https://github.com/symflower/eval-dev-quality/pull/256

2024-07-22 14:45 UTC, Munsio requested changes

2024-07-22 14:45 UTC, Munsio commented on cmd/eval-dev-quality/cmd/evaluate.go
> +	_ = assessmentsPerModel.WalkByScore(func(model string, assessment metrics.Assessments, score uint64) (err error) {
I guess this belongs to the refactoring commit?

2024-07-22 14:59 UTC, Munsio approved these changes

2024-07-22 15:04 UTC, merged