Check if the testdata repository is valid before running the evaluation, so it is checked just once
symflower/eval-dev-quality pull request #265
Opened 2024-07-12 15:49 UTC by ruiAzevedo19

Part of #263

2024-07-15 07:12 UTC, bauersimon requested changes

2024-07-15 07:12 UTC, bauersimon commented on evaluate/task/task-write-test_test.go
> +		})
I think at this point it would be cool to refactor this validation (and the `testCase`) out and reuse across the different tasks.

2024-07-15 07:12 UTC, bauersimon commented on evaluate/task/task-write-test_test.go
> +					defer file.Close()
Same suggestions as before. Please only create as many files as you need to trigger an error. And don't use `foo` and `bar` but what the entity actually is: `somefile`, `somepackage`, etc.

2024-07-15 09:32 UTC, ruiAzevedo19 commented on task/task.go
> +
Follow-up #266

2024-07-16 08:34 UTC, bauersimon commented on evaluate/task/task-code-repair_test.go
> +	}
Please move the `t.Run` into the actual validation function. That way you don't need to define your own here.

2024-07-16 09:44 UTC, merged