New task for code migration
symflower/eval-dev-quality pull request #376
Opened 2024-12-20 11:21 UTC by ruiAzevedo19

2024-12-20 13:01 UTC, bauersimon requested changes

2024-12-20 13:01 UTC, bauersimon commented on evaluate/task/migrate.go
> +	}
Would maybe track them in two slices and then sort them and use [`slices.Equal`](https://pkg.go.dev/slices#Equal).

2024-12-20 13:08 UTC, ruiAzevedo19 commented on evaluate/task/write-test.go
> +
Yap, good call

2024-12-20 13:12 UTC, ruiAzevedo19 commented on evaluate/task/symflower.go
> +func runModelAndSymflowerFix(ctx evaltask.Context, taskLogger *taskLogger, runTask func(model.Context) (metrics.Assessments, error), modelCtx model.Context, dataPath string, filePath string) (modelAs
I think it's fine for now

2024-12-20 13:19 UTC, ruiAzevedo19 commented on evaluate/task/migrate.go
> +		}
With both implementation files I was getting 50% coverage, after removing one of them I got 100% coverage

2024-12-20 13:51 UTC, bauersimon commented on evaluate/task/migrate.go
> +	}
I would still change cause it leaves less room for errors and is easier to read. Let's go clean code > usability here.

2025-01-06 09:30 UTC, ruiAzevedo19 commented on model/testing/helper.go
> +}
We have this for each task so I would keep it

2025-01-07 07:40 UTC, bauersimon commented on evaluate/task/migrate.go
> +		}
Yeah cause the other files are not covered then. We have the same "issue" with almost all other repositories. But we only count the absolute number of coverage objects anyways. I.e. 3x coverage objects. That number should be the same no matter if the other implementation files are there or not.

2025-01-07 07:48 UTC, bauersimon commented on model/testing/helper.go
> +}
Oke doke. Just keep in mind for the future.

2025-01-07 11:09 UTC, bauersimon commented on evaluate/task/migrate_test.go
> +					assert.Contains(t, data, "BUILD SUCCESS")
nitpick: is there some "evidence" in the logs that there were actually JUnit 5 tests that ran?

2025-01-07 11:09 UTC, bauersimon commented on evaluate/task/migrate_test.go
> +	}
nitpick: would maybe not use a helper here, just delete the files that you don't need one by one, cause this adds another complication layer :thinking:

2025-01-07 11:09 UTC, bauersimon commented on evaluate/task/migrate.go
> +		}
So I would simplify this function to just remove the test files. That way it is also the same as all other repositories.

2025-01-07 11:15 UTC, ruiAzevedo19 commented on evaluate/task/migrate_test.go
> +					assert.Contains(t, data, "BUILD SUCCESS")
AFAIK there is no such evidence

2025-01-07 11:57 UTC, bauersimon commented on evaluate/task/migrate.go
> +		}
Sorry for the confusion. I would still remove the test files. Just not the implementation ones.

2025-01-07 14:25 UTC, bauersimon commented on testdata/java/migrate-plain/pom.xml
> +		</dependency>
Todo remove so the model cannot just respond with JUnit4.

2025-01-07 14:30 UTC, bauersimon submitted a review, later dismissed

2025-01-08 07:59 UTC, merged